#!/bin/bash

DEFAULT_DAYS=30
DEFAULT_PORT=443
IN_FILE=domains.txt
HAS_HEADER_FILE=.has_header
RESULTS_FILE=results.txt

function echoerr() {
  echo "$@" >&2
}

function write_results {
  local server="$1"
  local expires_in="$2"
  local warn_days="${3}"
  local level=INFO
  if [[ $expires_in -le $warn_days ]]; then
    level=WARN
  fi
  local format="%-8s  %-40s  %-7s  %-7s\n"
  touch .has_header
  local has_header="$(cat .has_header)"
  if [[ ! $has_header ]]; then
    printf "$format" "# Level" Server "Exp. In" "Warn In" >"$RESULTS_FILE"
    echo "# ------------------------------------------------------------------" >>"$RESULTS_FILE"
    echo 1 >.has_header
  fi
  format="  %-6s  %-40s  %7s  %7s\n"
  printf "$format" $level $server $expires_in $warn_days >>"$RESULTS_FILE"
}

# echo the expiration date for server:port
function get_expiration_date {
  local serverport="$1"
  openssl s_client -connect $serverport 2>/dev/null </dev/null |
    openssl x509 -noout -enddate |
    cut -d= -f2
}

# return the number of days from other_date
# other_date must be in format of Sep 29 23:59:59 2023 GMT
function get_days_from_today {
  local other_date="$1"
  echo $((($(date --date "${other_date}" +%s) - $(date +%s)) / 86400))
}

rm -f "$HAS_HEADER_FILE"

if [[ ! -f $IN_FILE ]]; then
  if [[ -f $1 ]]; then
    IN_FILE="$1"
  else
    echoerr "Default file $IN_FILE not available, nor was one passed that could be read"
    exit 1
  fi
fi

echoerr "Certificate Expiration Check"
while read -r line; do
  pair="$(echo "$line" | awk -F= '{print $NF}')"
  serverport="$(echo $line | awk -F, '{print $1}')"
  if [[ ! $serverport =~ :[0-9]+$ ]]; then
    serverport="$serverport:$DEFAULT_PORT"
  fi
  warn_days="$(echo $line | awk -F, '{print $2}')"
  if [[ $warn_days == "" ]]; then
    warn_days=$DEFAULT_DAYS
  fi
  expires_on="$(get_expiration_date "$serverport")"
  echoerr "- $serverport"
  expires_in="$(get_days_from_today "$expires_on")"
  write_results $serverport $expires_in $warn_days
done <"$IN_FILE"

echoerr ""
cat "$RESULTS_FILE"
